name: Build and Release JoyRide Name Display

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg

      - name: Generate platform-specific icons
        run: |
          # Generate all platform icons
          echo "Generating cross-platform icons..."
          npm run generate-icons
          
          # Copy icons to build directory
          echo "Copying icons to build directory..."
          npm run copy-icons
          
          # List generated icons
          echo "Generated icons:"
          ls -la src/assets/icons/

      - name: Build distributables
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: joyride-${{ matrix.os }}
          path: out/make/**

  upload-release-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/joyride-*/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 